### ISSUE TITLE
wrong zimezone

### ISSUE THREAD

**Issue by Daniel-Berlin** [al-codaio/events-from-gmail#1]
HI,

i have a issue with the script. I hope i did everything right. But still i got the error messages:

I got the wrong timezone

i am in timezone GTM+2

Event created was GTM-5

-----------------------
I have to add for the date the correct year (2022). if i write just "22" it will be 1922
-----------------------
my system:

OS: Linux
Browser: Chrome
Timezone: gtm +2, Checked in OS and Google calendar

**Comment by Daniel-Berlin** [comment]
Timezone: solved

follow this youtube video. https://www.youtube.com/watch?v=nKIJchyAOus&t=5s

**Comment by thealchen** [comment]
@Daniel-Berlin glad you were able to figure this out! I also added the YouTube video to the comments on the original blog post.
