### ISSUE TITLE
I have to add for the date the correct year (2022). if i write just "22" it will be 1922

### ISSUE THREAD

**Issue by Daniel-Berlin** [al-codaio/events-from-gmail#2]
I have to add for the date the correct year (2022). if i write just "22" it will be 1922
if i write just: 1/4  (date format: ROW)  the date created will be first of april 2021

any ideas?

my system:

OS: Linux
Browser: Chrome

**Comment by thealchen** [comment]
Thanks for catching this @Daniel-Berlin! I updated the script with [this latest change](https://github.com/al-codaio/events-from-gmail/commit/39b77119819f3627b1ed0fede88a7b188418296b) so the script will always default to the current year. Originally I had hard-coded "2021" into the script which didn't make sense :).
